[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.4.0"
bitreader = "^0.3.4"
num-traits = "^0.2"
num-derive = "^0.3"

[profile.test]
opt-level = 3